model:
  base_learning_rate: 5e-5
  target: model.transformer_return.gpt_trainer_r_v7.GPT_stock_r
  params:
    moduleconfig:
      target: modules.transformers.base_v4.StockTransformer
      params:
        in_chans: 8
        num_classes: 73
        embed_dim: 96
        depth: 12
        output_dim: 1
        num_heads: 3
        mlp_ratio: 4.
        num_patches: 100
    feature_dim: 8
    obeserve_length: 24
    prediction_length: 1
    test_step: 1

data:
  target: main_candlestick.DataModuleFromConfig
  params:
    batch_size: 256
    num_workers: 4
    train:
      target: dataset.CSI_D_dataset.CSI_D_base
      params:
        config:
          root_path: ./data/CSI_D
          start_idx: 0
          end_idx: 1000   #only fit one day
          stock_start: 0
          num_stock: 50
          split: train
          repeat: 1600
          segment_length: 36  #24 for obsever 12 for predict
          stock_list:

    validation:
      target: dataset.CSI_D_dataset.CSI_D_base
      params:
        config:
          root_path: ./data/CSI_D
          # size: 256
          start_idx: 1000
          end_idx: 1284  #test the same day
          stock_start: 0
          num_stock: 50
          split: test
          repeat: 1
          segment_length: -1
          stock_list: