model:
  base_learning_rate: 5e-5
  target: model.transformer_return.gpt_trainer_r_v7_10_min.GPT_stock_r
  params:
    moduleconfig:
      target: modules.transformers.base_v4.StockTransformer
      params:
        in_chans: 8
        num_classes: 73
        embed_dim: 96
        depth: 12
        output_dim: 1
        num_heads: 3
        mlp_ratio: 4.
        num_patches: 100
    feature_dim: 8
    obeserve_length: 24
    prediction_length: 1
    test_step: 1
    interval_num: 6

data:
  target: main_candlestick.DataModuleFromConfig
  params:
    batch_size: 256
    num_workers: 4
    train:
      target: dataset.HK_5M_dataset.HK_5M_base
      params:
        config:
          root_path: ./data/HK_5M
          start_idx: 0
          end_idx: 60   #only fit one day
          stock_start: 0
          num_stock: 100
          split: train
          repeat: 128
          segment_length: 36  #24 for obsever 12 for predict
          stock_list:

    validation:
      target: dataset.HK_5M_dataset.HK_5M_base
      params:
        config:
          root_path: ./data/HK_5M
          # size: 256
          start_idx: 66
          end_idx: 73  #test the same day
          stock_start: 0
          num_stock: 100
          split: test
          repeat: 1
          segment_length: -1
          stock_list: [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 17, 18, 20, 21, 22, 24, 28, 30, 31, 34, 35, 36, 38, 39, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 55, 56, 57, 61, 62, 63, 65, 66, 67, 68, 69, 71]